import { useState, useEffect, useRef } from 'react';
import { CalendarDays, DollarSign, ShoppingCart, Package, Smartphone, Banknote, Tag, User, Printer } from 'lucide-react';
import useAuth from '../../hooks/useAuth';
import useTheme from '../../hooks/useTheme';
import { getEndOfDayReport } from '../../services/reportService';

const EndOfDayReport = () => {
  const { token } = useAuth();
  const { isDark } = useTheme();
  const [report, setReport] = useState(null);
  const [loading, setLoading] = useState(true);
  const [selectedDate, setSelectedDate] = useState(new Date().toISOString().split('T')[0]);
  const printRef = useRef(null);

  useEffect(() => { fetchReport(); }, [selectedDate]);

  const fetchReport = async () => {
    setLoading(true);
    try {
      const data = await getEndOfDayReport(token, selectedDate);
      setReport(data);
    } catch {
      setReport(null);
    } finally {
      setLoading(false);
    }
  };

  const handlePrint = () => {
    const content = printRef.current.innerHTML;
    const win = window.open('', '_blank');
    win.document.write(`
      <html><head><title>End of Day Report</title>
      <style>
        body { font-family: Arial, sans-serif; padding: 24px; color: #111; }
        h1 { font-size: 20px; margin-bottom: 4px; }
        p { font-size: 13px; color: #555; margin: 0 0 16px; }
        .grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 12px; margin-bottom: 20px; }
        .stat { border: 1px solid #e5e7eb; border-radius: 8px; padding: 12px; }
        .stat-label { font-size: 11px; color: #6b7280; margin-bottom: 4px; }
        .stat-value { font-size: 20px; font-weight: bold; color: #1d4ed8; }
        table { width: 100%; border-collapse: collapse; font-size: 13px; }
        th { text-align: left; padding: 8px; border-bottom: 2px solid #e5e7eb; font-size: 11px; color: #6b7280; text-transform: uppercase; }
        td { padding: 8px; border-bottom: 1px solid #f3f4f6; }
        .section-title { font-size: 14px; font-weight: 600; margin: 20px 0 8px; }
        .footer { margin-top: 32px; font-size: 11px; color: #9ca3af; text-align: center; }
      </style></head>
      <body>${content}
      <div class="footer">Generated by SwiftSale POS · ${new Date().toLocaleString('en-GH')}</div>
      </body></html>
    `);
    win.document.close();
    win.print();
  };

  const card = `rounded-xl p-5 ${isDark ? 'bg-slate-800' : 'bg-white'} shadow`;

  const stats = report ? [
    { label: 'Total Revenue', value: `GH₵ ${Number(report.totalRevenue).toFixed(2)}`, icon: DollarSign, color: 'text-rose-500' },
    { label: 'Transactions', value: report.totalTransactions, icon: ShoppingCart, color: 'text-green-500' },
    { label: 'Items Sold', value: report.totalItemsSold, icon: Package, color: 'text-yellow-500' },
    { label: 'Cash Collected', value: `GH₵ ${Number(report.totalCash).toFixed(2)}`, icon: Banknote, color: 'text-emerald-500' },
    { label: 'Mobile Money', value: `GH₵ ${Number(report.totalMobileMoney).toFixed(2)}`, icon: Smartphone, color: 'text-rose-500' },
    { label: 'Total Discounts', value: `GH₵ ${Number(report.totalDiscount).toFixed(2)}`, icon: Tag, color: 'text-rose-400' },
  ] : [];

  return (
    <div className="p-6">
      {/* Header */}
      <div className="flex justify-between items-center mb-6">
        <div>
          <h1 className={`text-2xl font-bold ${isDark ? 'text-white' : 'text-rose-800'}`}>End of Day Report</h1>
          <p className={`text-sm mt-1 ${isDark ? 'text-slate-400' : 'text-gray-500'}`}>Daily closing summary</p>
        </div>
        <div className="flex items-center gap-3">
          <div className="flex items-center gap-2">
            <CalendarDays size={16} className={isDark ? 'text-slate-400' : 'text-gray-400'} />
            <input
              type="date"
              value={selectedDate}
              onChange={(e) => setSelectedDate(e.target.value)}
              className={`border rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-rose-500 ${
                isDark ? 'bg-slate-700 border-slate-600 text-white' : 'bg-white border-gray-300 text-gray-800'
              }`}
            />
          </div>
          {report && report.totalTransactions > 0 && (
            <button
              onClick={handlePrint}
              className="flex items-center gap-2 bg-rose-600 hover:bg-rose-700 text-white px-4 py-2 rounded-lg text-sm font-medium transition shadow"
            >
              <Printer size={16} />
              Print Report
            </button>
          )}
        </div>
      </div>

      {loading ? (
        <div className="text-center py-16">
          <div className="w-8 h-8 border-4 border-rose-600 border-t-transparent rounded-full animate-spin mx-auto mb-2" />
          <p className={`text-sm ${isDark ? 'text-slate-400' : 'text-gray-500'}`}>Loading report...</p>
        </div>
      ) : !report || report.totalTransactions === 0 ? (
        <div className={`${card} text-center py-16`}>
          <CalendarDays size={40} className={`mx-auto mb-3 ${isDark ? 'text-slate-600' : 'text-gray-300'}`} />
          <p className={`font-semibold ${isDark ? 'text-slate-300' : 'text-gray-600'}`}>No transactions on this date</p>
          <p className={`text-sm mt-1 ${isDark ? 'text-slate-500' : 'text-gray-400'}`}>Try selecting a different date</p>
        </div>
      ) : (
        <div ref={printRef}>
          {/* Print header (visible in print) */}
          <div className="hidden print:block mb-4">
            <h1 style={{ fontSize: '20px', fontWeight: 'bold' }}>SwiftSale — End of Day Report</h1>
            <p style={{ fontSize: '13px', color: '#555' }}>
              {new Date(report.date).toLocaleDateString('en-GH', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}
            </p>
          </div>

          {/* Stats Grid */}
          <div className="grid grid-cols-3 gap-4 mb-6">
            {stats.map((s, i) => {
              const Icon = s.icon;
              return (
                <div key={i} className={card}>
                  <div className="flex items-center gap-3">
                    <div className={`p-2 rounded-lg ${isDark ? 'bg-slate-700' : 'bg-gray-50'}`}>
                      <Icon size={18} className={s.color} />
                    </div>
                    <div>
                      <p className={`text-xs ${isDark ? 'text-slate-400' : 'text-gray-500'}`}>{s.label}</p>
                      <p className={`text-lg font-bold ${isDark ? 'text-white' : 'text-gray-800'}`}>{s.value}</p>
                    </div>
                  </div>
                </div>
              );
            })}
          </div>

          {/* Cashier Breakdown */}
          {report.cashierBreakdown?.length > 0 && (
            <div className={card}>
              <div className="flex items-center gap-2 mb-4">
                <User size={16} className="text-rose-500" />
                <p className={`font-semibold text-sm ${isDark ? 'text-white' : 'text-gray-800'}`}>Cashier Breakdown</p>
              </div>
              <table className="w-full text-sm">
                <thead>
                  <tr className={`text-xs uppercase ${isDark ? 'text-slate-400' : 'text-gray-500'}`}>
                    <th className="text-left pb-3">Cashier</th>
                    <th className="text-right pb-3">Transactions</th>
                    <th className="text-right pb-3">Revenue</th>
                  </tr>
                </thead>
                <tbody>
                  {report.cashierBreakdown.map((c, i) => (
                    <tr key={i} className={`border-t ${isDark ? 'border-slate-700' : 'border-gray-100'}`}>
                      <td className={`py-3 font-medium ${isDark ? 'text-white' : 'text-gray-800'}`}>{c.name}</td>
                      <td className={`py-3 text-right ${isDark ? 'text-slate-300' : 'text-gray-600'}`}>{c.transactions}</td>
                      <td className="py-3 text-right font-semibold text-rose-500">GH₵ {Number(c.revenue).toFixed(2)}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </div>
      )}
    </div>
  );
};

export default EndOfDayReport;
